### ISSUE TITLE
jcuda-natives-10.1.0-windows-x86_64.pom is missed in the maven repository

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcuda-parent#1] opened 2019-09-29 09:07 UTC
jcuda-natives-10.1.0-windows-x86_64.pom is missed in the central maven repository while corresponding jar exists
If somebody will take this issue, please correct code compliance to 1.7 because recent eclipse doesn't support 1.6 any more
My development landscape:
Version: 2019-09 R (4.13.0) with jdk 13 on Windows 10 machine with Geforse 2060 and Nvidia toolkit 10.1 patch 2 installed
P.S. If some help in testing on such configuration is needed I still have time to assist

**Comment by jcuda** [comment] 2019-09-29 12:58
I wouldn't consider myself as a Maven expert, so please correct me if I'm wrong here: The actual *artifact* for the native libraries is `jcuda-natives-10.1.0`, and the corresponding POM is at https://repo1.maven.org/maven2/org/jcuda/jcuda-natives/10.1.0/jcuda-natives-10.1.0.pom

The remaining part, `windows-x86_64` in your example, is the *classifier*. As of https://maven.apache.org/pom.html

> The classifier distinguishes artifacts that were built from the same POM but differ in content.

So there is no dedicated POM for each of them, as the `jcuda-natives-10.1.0.pom` is the common one.

> If somebody will take this issue, please correct code compliance to 1.7 because recent eclipse doesn't support 1.6 any more

A full-text search showed that `1.6` is (only) used in the `jcuda-samples`, and `jcuda-utils` and `jcuda-matrix-utils`, whereas the main parent POM uses `1.7`. Usually, I think the compliance should be "as low as possible for it to work", and there are no >1.6 features used, actually. But I'll consider updating that. I assume that you mainly referred to the `jcuda-samples`, right?

**Comment by PavelSosin-320** [comment] 2019-10-01 05:22
Unfortunately, as results of Maven repository request [SearchJcuda natives for Windows 64 ](https://search.maven.org/classic/#search%7Cga%7C1%7Cg%3A%22org.jcuda%22%20AND%20a%3A%22jcuda-natives%22%20AND%20l%3A%22windows-x86_64%22) show pom is missed only for Windows 64. Dependency with Cuda-natives with qualifier windows-x86_64 gave me error in maven build - artifact can't be found. As aresult neither sample which I ran founded its DLL
Regarding compliance: I can't judge the desicion of eclipse and maven teams to terminate support of compliance with level 1.5 and 1.6 but I tried with compliance level 1.7 and everything was built OK
Yet another issue is javadoc generation for jcuda native which fails because can't find files to process. I solved it using javadoc pluging configuration:
`            	<groupId>org.apache.maven.plugins</groupId>
            	<artifactId>maven-javadoc-plugin</artifactId>
            	<version>3.1.1</version>
            	<configuration>
            		<skip>true</skip>
            	</configuration>
            </plugin>`

**Comment by jcuda** [comment] 2019-10-01 17:29
Maybe I misunderstood the issue in the first place. 

To start further from the top: When you want to use JCuda, you *only* have to add 

    <dependency>
        <groupId>org.jcuda</groupId>
        <artifactId>jcuda</artifactId>
        <version>10.1.0</version>
    </dependency>

to your POM. It should **not** be necessary to specify which `natives` you need. (That's the whole point of some tedious POM gymnastics that I had to make when bringing JCuda into Maven Central...)

The `jcuda` part has a dependency to `jcuda-natives`, and the classifier (i.e. whether it is Windows or Linux or MacOS) will be determined automatically for the target system, based on the profile (details can be found at https://github.com/jcuda/jcuda-parent/blob/master/pom.xml#L41 )

So to phrase it that way: Which problem exactly did you encounter, and did you encounter that problem even when you *only* added the `jcuda` dependency (and not any `jcuda-natives` dependency) to your POM?

**Comment by PavelSosin-320** [comment] 2019-10-02 14:11
I created naked maven project with single dependency jcuda 10.1.0 and maven build answers me The _POM for jcuda.org:jcuda:jar:windows-x86_64:10.1.0 is missing, no dependency information available._ Maven needs it to download jcuda dependencies recursively or build dependecies locally. Indeed jar files exist in maven repository for Windows64 but pom file is missed. Working with local maven repository on your computer is simple but It is not so simple to publish package to central. see [Publish instruction](https://maven.apache.org/repository/guide-central-repository-upload.html). If you are connected to some java DEvOps pipeline this dirty job is done by certain Jenkins job after surfire maven plugin reported that all tests are green.

**Comment by PavelSosin-320** [comment] 2019-10-02 14:47
Regarding supported source version - this is proper technical problem of maven compiler plugin embedded into eclipse or delivered with maven standalone. This issued was closed wuth the following recomendation - set to 1.8 [Setting the -source and -target of the Java Compiler](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html) from Maven

**Comment by jcuda** [comment] 2019-10-02 16:16
I also just created a new, fresh Maven project (in Eclipse), deleted my whole local `\.m2\repository\org\jcuda` folder, added the JCuda dependency to the maven project and hit "build", and it worked (sorry, that doesn't help you, but I tried to reproduce the issue).

I know that the process of publishing things on Maven implies many constraints. Most of them are usually handled by the maven release plugin. But for JCuda, the fact that the natives have to be built for the specific target platforms and have to be provided by several contributors makes things difficult. Therefore, I manually have to create the bundles that are then uploaded via https://oss.sonatype.org/ . There *can* be an issue with that - the creation of the bundles involves (shame on me: ) some .BAT files and manual signing of files with GPG. However, there are several uses of JCuda libraries from Maven Central (for the current and older versions), so I hope that this is not a *general* problem...

So I'm not entirely sure how to debug this further. Maybe one step would be sharing the build output. A `mvn clean package` at the command line in the test project that I created prints

    [INFO] ------------------------------------------------------------------------
    [INFO] Building test 0.0.1-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    Downloading: https://repo.maven.apache.org/maven2/org/jcuda/jcuda/10.1.0/jcuda-10.1.0.pom
    Downloaded: https://repo.maven.apache.org/maven2/org/jcuda/jcuda/10.1.0/jcuda-10.1.0.pom (2 KB at 2.6 KB/sec)
    Downloading: https://repo.maven.apache.org/maven2/org/jcuda/jcuda-parent/10.1.0/jcuda-parent-10.1.0.pom
    Downloaded: https://repo.maven.apache.org/maven2/org/jcuda/jcuda-parent/10.1.0/jcuda-parent-10.1.0.pom (7 KB at 101.9 KB/sec)
    Downloading: https://repo.maven.apache.org/maven2/org/jcuda/jcuda-natives/10.1.0/jcuda-natives-10.1.0.pom
    Downloaded: https://repo.maven.apache.org/maven2/org/jcuda/jcuda-natives/10.1.0/jcuda-natives-10.1.0.pom (4 KB at 64.2 KB/sec)
    Downloading: https://repo.maven.apache.org/maven2/org/jcuda/jcuda-natives/10.1.0/jcuda-natives-10.1.0-windows-x86_64.jar
    Downloading: https://repo.maven.apache.org/maven2/org/jcuda/jcuda/10.1.0/jcuda-10.1.0.jar
    Downloaded: https://repo.maven.apache.org/maven2/org/jcuda/jcuda-natives/10.1.0/jcuda-natives-10.1.0-windows-x86_64.jar (322 KB at 1000.7 KB/sec)
    Downloaded: https://repo.maven.apache.org/maven2/org/jcuda/jcuda/10.1.0/jcuda-10.1.0.jar (167 KB at 488.5 KB/sec)
    [INFO]

So it is explicitly (only) looking for and downloading the `jcuda-natives-10.1.0.pom`, and not any other `natives...pom`. What does it print for you?

---

(Regarding the version issue: Again, which project are you referring to, exactly? The `jcuda-samples`?)

**Comment by jcuda** [comment] 2019-10-18 16:24
Closing because there does not seem to be any further activity.

**Closed as completed by jcuda** 2019-10-18 16:24 UTC
